spring.application.name=order-service
server.port=8083
spring.config.import=optional:configserver:http://localhost:9999

logging.level.net.anas.order_service.services.CustomerRestClientService=debug
logging.level.net.anas.order_service.services.InventoryRestClientService=debug
#logging.level.feign=DEBUG
#spring.cloud.openfeign.client.config.default.logger-level=full
##feign.client.config.default.loggerLevel=full