spring.application.name=billing-service
server.port=8084
#spring.config.import=optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999},consul://${SPRING_CLOUD_CONSUL_HOST:localhost}:${SPRING_CLOUD_CONSUL_PORT:8500}/config/billing-service,vault://secret/billing_service
spring.config.import=consul:,vault://
spring.cloud.consul.config.fail-fast=false
#h2
spring.datasource.url=jdbc:h2:mem:bill-db
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
#consul
spring.cloud.consul.host=${SPRING_CLOUD_CONSUL_HOST:localhost}
spring.cloud.consul.port=${SPRING_CLOUD_CONSUL_PORT:8500}
spring.cloud.consul.config.enabled=true
spring.cloud.consul.discovery.enabled=true
spring.cloud.consul.config.prefixes=config
spring.cloud.consul.config.default-context=billing-service
#logging.level.org.springframework.cloud=DEBUG
#logging.level.org.springframework.boot.context.config=DEBUG

#vault
spring.cloud.vault.token=${SPRING_CLOUD_VAULT_TOKEN:dev-root-token}
spring.cloud.vault.host=${SPRING_CLOUD_VAULT_HOST:localhost}
spring.cloud.vault.port=${SPRING_CLOUD_VAULT_PORT:8200}
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.default-context=billing_service
spring.cloud.vault.scheme=http
spring.cloud.vault.kv.enabled=true

management.endpoints.web.exposure.include=*


