spring.application.name=config-service
server.port=9999
#spring.cloud.config.server.git.uri=file://D:/2025-2026-supmti/MicroService/ecomMicroService/ecom_micro_service_app/Config-repo
spring.cloud.config.server.git.uri=https://github.com/Anas-MZAATER/ecom_micro_service_config_repo.git